auto-commit

diff --git a/commandlock_test b/commandlock_test
--- a/commandlock_test
+++ b/commandlock_test
@@ -1,10 +1,10 @@
 #!/bin/sh
 
 echo "[$$] $0 in a non-critical section, about to acquire lock"
-. /usr/bin/command-lock
+. /usr/bin/commandlock
 echo "[$$] $0 in a critical section, about to test lock"
 
-/usr/bin/command-lock-test && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
+/usr/bin/commandlock_test && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
     echo "[$$] $0 YOU SHOULD SEE 2 ERROR MESSAGES WITH THE SAME PID != [$$]"
     echo "[$$] $0 You shoud NOT see a message starting with \"unlink: cannot unlink\""
-    echo "[$$] $0 Lock test completed sucessfully."
+    echo "[$$] $0 Lock test completed."
