test source requirement

diff --git a/commandlock_test b/commandlock_test
--- a/commandlock_test
+++ b/commandlock_test
@@ -1,6 +1,23 @@
 #!/bin/sh
 
-# TODO: test the #! echo
+
+#echo "[$$] $0 Testing source requirement."
+msg_bang=`commandlock`
+if [ -z "${msg_bang##source_this_file*}" ];
+then
+    :
+else
+    echo "[$$] $0 source requirement test failed on #! execution."
+    exit 1
+fi
+
+echo "[$$] $0 Finding absolute path of commandlock for bash execution test."
+path=`whereis commandlock | cut -d ' ' -f 2`
+bash "${path}" && { echo "[$$] $0 bash execution test failed." ; exit 1 ; }
+
+
+#echo "[$$] $0 Source requirement tests passed."
+
 
 echo "[$$] $0 in a non-critical section, about to acquire lock"
 . commandlock
