auto-commit

diff --git a/shell-command-lock b/shell-command-lock
--- a/shell-command-lock
+++ b/shell-command-lock
@@ -8,7 +8,7 @@ type sha1sum > /dev/null || return
 readonly lock_folder_scl="/dev/shm"
 
 if [ ! -d "${lock_folder_scl}" ]; then
-    printf "ERROR: [$$] $0 $* %s not a directory.\n" "${lock_folder_scl}" >&2
+    printf 'ERROR: [$$] $0 $* %s not a directory.\n' "${lock_folder_scl}" >&2
     exit 1
 fi
 
