Added checks, switched to noclobber from mkdir, more documentation

diff --git a/shell_command_lock b/shell_command_lock
--- a/shell_command_lock
+++ b/shell_command_lock
@@ -1,57 +1,106 @@
-#!/bin/bash
+#!/bin/sh
 #
 # PUBLIC DOMAIN
 #
-# shell_command_lock - prevent identical bash/sh command lines from executing
-# concurrently. A command line is the command and it's arguments:
-# $0 $*
+# shell_command_lock - Atomic locking for shell commands.
 #
-# Steps:
-#	1. Generate unique and reproducible string from $0 $* that can
-#          be represented as a directory name. Sha1($0 $*) is used.
-#
-#	2. Obtain atomic lock via mkdir
-#
-# More info:
-# http://wiki.bash-hackers.org/howto/mutex
-# http://mywiki.wooledge.org/BashFAQ/045
-#
-#
-# Install: Place this script in your $PATH. For example:
-#
-# mkdir ~/bin && \
-# ln -s ~/repos/shell_command_lock ~/bin/shell_command_lock && \
-# echo "$PATH" | grep ~/bin || \
-# { echo "add PATH=$PATH:$HOME/bin to ~/.bash_profile" ; } && \
-# echo "~/bin is in your PATH. All set."
-#
-# Usage: Add the line:
-#
-# source sh_exclusive_command_lock
-#
-# before the critical section in your script. The lock will be removed when the
-# parent script terminates (see trap below).
+# Prevent identical command lines from executing concurrently.
+# A command line is the combination of the command and it's arguments: $0 $*
 #
 # Requires: sha1sum
 #
+# Steps:
+#	1. Generate unique and reproducible string from $0 $* that can
+#          be represented as a file name. sha1($0 $*) is used.
+#
+#	2. Obtain atomic lock
+#
+# More info:
+# http://www.davidpashley.com/articles/writing-robust-shell-scripts.html
+# http://wiki.bash-hackers.org/howto/mutex
+# http://mywiki.wooledge.org/BashFAQ/045
+# http://wiki.grzegorz.wierzowiecki.pl/code:mutex-in-bash
+# http://code.google.com/p/pylockfile/
+#
+# Notes:
+#	This script attempts to strictly POSIX (no extensions) compliant.
+#
+#	Redirection using noclobber is the atomic locking primitive used
+#	instead of mkdir because in it's faster.
+#
+#	Benchmarks:
+#		time for x in {1..24000} ; do mkdir lock ; rmdir lock ; done
+#
+#		time for x in {1..24000} ; do set -o noclobber; : > lock ; \
+#		unlink lock ; done
+#
+#
+# Install: Place in $PATH.
+#
+# mkdir ~/bin ; mv shell_command_lock ~/bin/shell_command_lock
+#
+# To use, insert:
+#
+# source shell_command_lock
+#
+# before the critical section in the parent script. The lock is removed when
+# the parent script terminates via the trap below.
+#
+#
+# Unknown Bugs:
+#
+#	Exist. Fixes/improvements/suggestions appreciated.
+#
+#	This script should have no effect on the parent script other
+#	than locking.
+#
+#	The variable names used have random strings appended to prevent
+#	collisions with common names like $lock in the parent script.
+#
+#	The set commands are done in subshells so we don't need to save and
+#	restore the state.
+#
+# Known Bugs:
+#
+#	1. IMPORTANT: If the trap is re-defined in the parent script,
+#		      then that trap will need to handle deleting the lock.
+#
+#	2. The lockfile is orphaned if a exit signal happens after the lock
+#	   is obtained and before trap is set.
 #
 
-lockdir_name=$(echo $0 $* | sha1sum | cut -d ' ' -f 1)
-lockdir="/dev/shm/${lockdir_name}" 	# using tempfs so we loose orphaned and
-					# old lockdirs on reboot
 
-remove_lock()	#mv is safer than rm, as a bonus we get a lock history
-{
-        timestamp=$(date +%s.%N) || echo "Unable to get timestamp"
-        mv -- "${lockdir}" "${lockdir}.old.lock.${timestamp}"
-}
+lock_folder_99c850a32="/dev/shm" 	#using tempfs to delete orphaned
+					#locks on reboot
 
-if ! mkdir "${lockdir}" 2>/dev/null; then
-    echo "$0 $* is already running." >&2
-    exit 1
+if [ ! -d "${lock_folder_99c850a32}" ]; then
+	echo "Error: ${lock_folder_99c850a32} is not a directory. Exiting." >&2
+	exit 1
 fi
 
-trap remove_lock ERR INT TERM EXIT	# is this a complete list?
 
-# Note that if you CTRL-c the parent script, remove_lock() may get called
-# more than once.
+lock_name_99c850a32=$(set -o pipefail ; \
+		      echo "$0 $*" | sha1sum | cut -d ' ' -f 1) \
+	|| { echo "Error generating lock_name. Exiting" >&2 ; exit 1 ; }
+
+
+if [ "${#lock_name_99c850a32}" != "40" ]; then
+	echo "Error: lock_name \"${lock_name_99c850a32}"\"
+	echo "is not (sha1) 40 bytes long. Exiting" >&2
+	exit 1
+fi
+
+
+lock_99c850a32="${lock_folder_99c850a32}/lock_${lock_name_99c850a32}"
+
+
+if ( set -o noclobber; : > "${lock_99c850a32}" ) 2> /dev/null; then #got a lock
+	# setting trap asap
+	trap 'unlink -- "${lock_99c850a32}" ; exit $?' \
+	INT HUP ALRM PIPE PROF USR1 USR2 VTALRM STKFLT QUIT ABRT TERM EXIT
+#  	echo "Locking succeeded: ${lock_99c850a32}" >&2
+else
+	echo "Locking failed: ${lock_99c850a32} - Exiting" >&2
+	echo "$0 $* is already running." >&2
+	exit 1
+fi
