prob a bug on line15

diff --git a/shell-command-lock b/shell-command-lock
--- a/shell-command-lock
+++ b/shell-command-lock
@@ -7,13 +7,12 @@ type sha1sum > /dev/null || return
 # use tempfs to delete orphaned locks on reboot
 lock_folder_scl="/dev/shm"
 
-if [ ! -d "${lock_folder_scl}" ]; then
-    printf 'ERROR: [$$] $0 $* %s not a directory.\n' "${lock_folder_scl}" >&2
+if [ ! -d "${lock_folder_scl}" ]; then # todo: add test for this... not sure how
+    printf 'ERROR: [%s] %s %s %s not a directory.\n' "$$" "$0" "$@" "${lock_folder_scl}" >&2
     exit 1
 fi
 
-lock_name_scl=$(printf '%s\0' "$0" "$@" | sha1sum -) && lock_name_scl=${lock_name_scl%% *} \
-    || { printf "ERROR: [%s] %s %s generating lock filename.\n" "$$" "$0" "$@" >&2 ; exit 1 ; }
+lock_name_scl=$(printf '%s\0' "$0" "$@" | sha1sum -) && lock_name_scl=${lock_name_scl%% *} || { printf "ERROR: [%s] %s %s generating lock filename.\n" "$$" "$0" "$@" >&2 ; exit 1 ; }
 
 if [ "${#lock_name_scl}" != "40" ]; then
     printf "ERROR: [%s] %s %s lock_name \"%s\"is not 40 bytes long.\n" "$$" "$0" "$@" "${lock_name_scl}" >&2
