auto-commit

diff --git a/shell-command-lock b/shell-command-lock
--- a/shell-command-lock
+++ b/shell-command-lock
@@ -2,7 +2,7 @@
 # shell_command_lock - Atomic locking for commands.
 # https://github.com/jakeogh/shell-command-lock
 
-type sha1sum > /dev/null || return
+type sha1sum > /dev/null || { printf 'ERROR: [%s] sha1sum not found.\n' "$$" ; exit 1 ; }
 
 # use tempfs to delete orphaned locks on reboot
 lock_folder_scl="/dev/shm"
@@ -25,7 +25,7 @@ lock_name_scl=${lock_name_scl%% *} || {
 if [ "${#lock_name_scl}" != "40" ]; then
     printf >&2 "ERROR: [%s] %s %s lock_name \"%s\"is not 40 bytes long.\n" \
         "$$" "$0" "$*" "${lock_name_scl}"
-    exit 1
+     exit 2
 fi
 
 readonly lock_scl="${lock_folder_scl}/lock_${lock_name_scl}"
