remove cut and pipefail bashisim, use NULL delmims per geirha

diff --git a/shell-command-lock b/shell-command-lock
--- a/shell-command-lock
+++ b/shell-command-lock
@@ -12,11 +12,11 @@ if [ ! -d "${lock_folder_scl}" ]; then
     exit 1
 fi
 
-readonly lock_name_scl=$(printf "%s\0" "$0" "$*" | sha1sum -) \
-    || { printf "ERROR: [%s] %s %s generating lock_name.\n" "$$" "$0" "$*" >&2 ; exit 1 ; }
+readonly lock_name_scl=$(printf '%s\0' "$0" "$@" | sha1sum -) && lock_name_scl=${lock_name_scl%% *} \
+    || { printf "ERROR: [%s] %s %s generating lock filename.\n" "$$" "$0" "$@" >&2 ; exit 1 ; }
 
 if [ "${#lock_name_scl}" != "40" ]; then
-    printf "ERROR: [%s] %s %s lock_name \"%s\"is not 40 bytes long.\n" "$$" "$0" "$*" "${lock_name_scl}" >&2
+    printf "ERROR: [%s] %s %s lock_name \"%s\"is not 40 bytes long.\n" "$$" "$0" "$@" "${lock_name_scl}" >&2
     exit 1
 fi
 
@@ -31,7 +31,7 @@ if ( set -o noclobber; : > "${lock_scl}" ) 2> /dev/null; then # got lock
 
     printf "%s" "$$">> "${lock_scl}"
 else
-    printf "ERROR: [%s] %s %s Locking failed: %s\n" "$$" "$0" "$*" "${lock_scl}" >&2
-    printf "ERROR: [%s] %s %s is/was already running. Exiting (1).\n" "$$" "$0" "$*" >&2
+    printf "ERROR: [%s] %s %s Locking failed: %s\n" "$$" "$0" "$@" "${lock_scl}" >&2
+    printf "ERROR: [%s] %s %s is/was already running. Exiting (1).\n" "$$" "$0" "$@" >&2
     exit 1
 fi
