auto-commit

diff --git a/shell-command-lock-test b/shell-command-lock-test
--- a/shell-command-lock-test
+++ b/shell-command-lock-test
@@ -1,14 +1,10 @@
 #!/bin/sh
 
 echo "[$$] $0 in a non-critical section, about to acquire lock"
-
 . /usr/bin/shell-command-lock
-
 echo "[$$] $0 in a critical section, about to test lock"
 
-./test_locking && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
+/usr/bin/shell-command-lock-test && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
     echo "[$$] $0 You should see 2 error messages with the same PID != [$$]"
     echo "[$$] $0 You shoud NOT see a message starting with \"unlink: cannot unlink\""
     echo "[$$] $0 Lock test completed sucessfully."
-
-exit 0
